import Foundation

struct ResolvedFileContext: Sendable, Equatable {
    let reference: String
    let relativePath: String
    let contents: String
    let wasTruncated: Bool
}

struct ProjectContextService: Sendable {
    private let skippedDirectories: Set<String> = [
        ".git", ".build", ".swiftpm", "DerivedData", "node_modules", ".idea", ".vscode", "__MACOSX"
    ]

    private let skippedFiles: Set<String> = [
        ".DS_Store"
    ]

    func workspaceRoot(from path: String) -> URL {
        URL(fileURLWithPath: (path as NSString).expandingTildeInPath).standardizedFileURL
    }

    func promptPrefix(for path: String) -> String {
        let root = workspaceRoot(from: path)
        let name = root.lastPathComponent.isEmpty ? "~" : root.lastPathComponent
        return "ghost@local \(name) %"
    }

    func listFiles(
        root: URL,
        matching query: String? = nil,
        limit: Int = 80
    ) -> [String] {
        let cleanQuery = query?.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        let allFiles = collectFiles(root: root, limit: max(limit * 4, limit))

        guard let cleanQuery, !cleanQuery.isEmpty else {
            return Array(allFiles.prefix(limit))
        }

        return Array(
            allFiles
                .filter { $0.lowercased().contains(cleanQuery) }
                .prefix(limit)
        )
    }

    func createGhostInstructions(root: URL) throws -> String {
        let instructionURL = root.appendingPathComponent("GHOST.md")
        let fileList = listFiles(root: root, limit: 120)
        let existing = FileManager.default.fileExists(atPath: instructionURL.path)

        let contents = """
        # Ghost Project Instructions

        Generated by Ghost Terminal Mode.

        ## Project root
        `\(root.path)`

        ## How Ghost should work in this project
        - Prefer small, reviewable patches.
        - Explain the plan before large edits.
        - Run the relevant build or test command after code changes.
        - Never edit secrets, `.env`, credentials, or generated build output.
        - Use `@path/to/file` references when the user points at specific files.
        - Use `!command` output as ground truth for shell state.

        ## Current project map
        \(fileList.map { "- \($0)" }.joined(separator: "\n"))
        """

        try contents.write(to: instructionURL, atomically: true, encoding: .utf8)
        return existing ? "Updated GHOST.md" : "Created GHOST.md"
    }

    func resolvedFileContexts(
        in prompt: String,
        root: URL,
        maxFiles: Int = 6,
        maxBytesPerFile: Int = 16_000
    ) -> [ResolvedFileContext] {
        let references = fileReferences(in: prompt)
        guard !references.isEmpty else { return [] }

        return references.prefix(maxFiles).compactMap { reference in
            try? readFileReference(reference, root: root, maxBytes: maxBytesPerFile)
        }
    }

    func readFileReference(
        _ reference: String,
        root: URL,
        maxBytes: Int = 16_000
    ) throws -> ResolvedFileContext {
        let cleanReference = reference
            .trimmingCharacters(in: CharacterSet(charactersIn: "@`'\" "))
            .trimmingCharacters(in: .whitespacesAndNewlines)

        let candidates = candidateURLs(for: cleanReference, root: root)
        guard let url = candidates.first(where: { isReadableFile($0, inside: root) }) else {
            throw ProjectContextError.fileNotFound(cleanReference)
        }

        let data = try Data(contentsOf: url)
        let wasTruncated = data.count > maxBytes
        let clippedData = wasTruncated ? data.prefix(maxBytes) : data[...]
        guard var contents = String(data: clippedData, encoding: .utf8) else {
            throw ProjectContextError.notText(url.path)
        }
        if wasTruncated {
            contents += "\n\n[truncated at \(maxBytes) bytes]"
        }

        return ResolvedFileContext(
            reference: cleanReference,
            relativePath: relativePath(for: url, root: root),
            contents: contents,
            wasTruncated: wasTruncated
        )
    }

    func fileReferences(in prompt: String) -> [String] {
        guard let regex = try? NSRegularExpression(pattern: #"@([A-Za-z0-9_./+\-]+)"#) else {
            return []
        }

        let range = NSRange(prompt.startIndex..<prompt.endIndex, in: prompt)
        let matches = regex.matches(in: prompt, range: range)
        var seen = Set<String>()
        var references: [String] = []

        for match in matches {
            guard
                match.numberOfRanges > 1,
                let swiftRange = Range(match.range(at: 1), in: prompt)
            else { continue }

            let reference = String(prompt[swiftRange])
            if seen.insert(reference).inserted {
                references.append(reference)
            }
        }
        return references
    }

    private func collectFiles(root: URL, limit: Int) -> [String] {
        guard let enumerator = FileManager.default.enumerator(
            at: root,
            includingPropertiesForKeys: [.isDirectoryKey, .isRegularFileKey],
            options: [.skipsHiddenFiles]
        ) else { return [] }

        var files: [String] = []
        for case let url as URL in enumerator {
            let name = url.lastPathComponent
            if skippedDirectories.contains(name) {
                enumerator.skipDescendants()
                continue
            }
            if skippedFiles.contains(name) { continue }

            let values = try? url.resourceValues(forKeys: [.isDirectoryKey, .isRegularFileKey])
            if values?.isDirectory == true { continue }
            guard values?.isRegularFile == true else { continue }

            files.append(relativePath(for: url, root: root))
            if files.count >= limit { break }
        }
        return files.sorted()
    }

    private func candidateURLs(for reference: String, root: URL) -> [URL] {
        var candidates: [URL] = []
        let direct = root.appendingPathComponent(reference).standardizedFileURL
        candidates.append(direct)

        let basename = URL(fileURLWithPath: reference).lastPathComponent
        if basename != reference {
            candidates.append(root.appendingPathComponent(basename).standardizedFileURL)
        }

        let matches = listFiles(root: root, matching: basename, limit: 10)
            .map { root.appendingPathComponent($0).standardizedFileURL }
        candidates.append(contentsOf: matches)

        var seen = Set<String>()
        return candidates.filter { seen.insert($0.path).inserted }
    }

    private func isReadableFile(_ url: URL, inside root: URL) -> Bool {
        let rootPath = root.standardizedFileURL.path
        let filePath = url.standardizedFileURL.path
        guard filePath == rootPath || filePath.hasPrefix(rootPath + "/") else {
            return false
        }

        var isDirectory: ObjCBool = false
        guard FileManager.default.fileExists(atPath: filePath, isDirectory: &isDirectory), !isDirectory.boolValue else {
            return false
        }
        return FileManager.default.isReadableFile(atPath: filePath)
    }

    private func relativePath(for url: URL, root: URL) -> String {
        let rootPath = root.standardizedFileURL.path
        let filePath = url.standardizedFileURL.path
        if filePath.hasPrefix(rootPath + "/") {
            return String(filePath.dropFirst(rootPath.count + 1))
        }
        return filePath
    }
}

enum ProjectContextError: LocalizedError {
    case fileNotFound(String)
    case notText(String)

    var errorDescription: String? {
        switch self {
        case .fileNotFound(let path):
            "Could not find @\(path) in the current workspace."
        case .notText(let path):
            "Could not read \(path) as UTF-8 text."
        }
    }
}
